// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK5FIAvFWTyf0SbPEBFClQFQftxSJ1Xtw',
    appId: '1:632694209747:web:781c429f95151ab8432826',
    messagingSenderId: '632694209747',
    projectId: 'evoting-system-34d6d',
    authDomain: 'evoting-system-34d6d.firebaseapp.com',
    storageBucket: 'evoting-system-34d6d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaIgWXDEKzDJR16UnYyF-AjoInDmuYFtI',
    appId: '1:632694209747:android:81b27ec736fb4372432826',
    messagingSenderId: '632694209747',
    projectId: 'evoting-system-34d6d',
    storageBucket: 'evoting-system-34d6d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD7hCyGoMmK5C9IQzluMG-1_lQjKnBL4A',
    appId: '1:632694209747:ios:b6cfd1f122d2ebdd432826',
    messagingSenderId: '632694209747',
    projectId: 'evoting-system-34d6d',
    storageBucket: 'evoting-system-34d6d.firebasestorage.app',
    iosBundleId: 'com.s4k1l.evotingsystem',
  );
}
